package Test::Apocalypse::Fixme;

# ABSTRACT: Plugin for Test::Fixme

use Test::More;
use Test::Fixme 0.04;

sub _is_release { 1 }
sub _is_todo { 1 }

sub do_test {
	TODO: {
		local $TODO = "Fixme";
		run_tests(
			'where'			=> 'lib',
			'match'			=> qr/[F]IXME|[T]ODO|[X]XX/,
			'filename_match'	=> qr/\.(?:pm|pl|xs)$/, # specify this so we skip .c files generated by XS
		);
	}

	return;
}

1;

=pod

=for Pod::Coverage do_test

=head1 DESCRIPTION

Encapsulates L<Test::Fixme> functionality.

=cut
