package Test::Apocalypse::Fixme;

# ABSTRACT: Plugin for Test::Fixme

sub _is_release { 1 }

use Test::Fixme 0.04;

sub do_test {
	TODO: {
		local $TODO = $TODO = "This is an 'informational' test and shouldn't FAIL";

		run_tests(
			'where'			=> 'lib',
			'match'			=> qr/[F]IXME|[T]ODO|[X]XX/,
			'filename_match'	=> qr/\.(?:pm|pl|xs)$/, # specify this so we skip .c files generated by XS
		);
	}

	return;
}

1;

=pod

=for Pod::Coverage do_test

=head1 DESCRIPTION

Encapsulates L<Test::Fixme> functionality.

=cut
